# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

[package]
name = "dpdk-rs"
version = "1.0.1"
edition = "2018"

[dependencies]
cfg-if = "1.0.0"

[build-dependencies]
bindgen = "0.59.2"
cc = "1.0"

[features]
mlx4 = []
mlx5 = []
